export const pricingData = {
  men_haircut: [
    { service: "Haircut by VM", price: 250 },
    { service: "Haircut by Staff", price: 200 },
    { service: "Beard by VM", price: 200 },
    { service: "Beard by Staff", price: 150 },
    { service: "Beard without slope", price: 100 },
    { service: "Beard trim", price: 50 },
    { service: "Hair wash & styling", price: 100 },
  ],
  women_haircut: [
    { service: "Haircut by VM", price: 700 },
    { service: "Haircut by Staff", price: 600 },
    { service: "Hair Wash", price: 300 },
    { service: "Hair Wash & Styling", price: 450 },
  ],
  hair_styling: [
    { service: "Ironing upto waist", price: 500 },
    { service: "Ironing below waist", price: 800 },
    { service: "Tong upto waist", price: 500 },
    { service: "Tong below waist", price: 800 },
  ],
  men_hair_color: [
    { brand: "Matrix Global", short: 550, medium: 650, long: 950 },
    { brand: "Loreal Majirel", short: 650, medium: 750, long: 1150 },
    { service: "Beard Colour Matrix", short: 200, medium: 250, long: 300 },
    { service: "Beard Colour Loreal", short: 300, medium: 350, long: 400 },
    { service: "Moustache Colour", price: 50 },
    { service: "Highlights", short: 1000, medium: 1200, long: 1500 },
  ],
  women_hair_color: [
    { service: "Global Color Matrix", shoulder: 2000, below: 3500, waist: 5500 },
    { service: "Global Color Loreal", shoulder: 2200, below: 3700, waist: 5700 },
    { service: "Fashion Color", shoulder: 2500, below: 4000, waist: 6000 },
    { service: "Highlights", shoulder: 2500, below: 4000, waist: 6000 },
    { service: "Ombre", shoulder: 2500, below: 3500, waist: 4500 },
    { service: "Balayage", shoulder: 3000, below: 5000, waist: 7000 },
    { service: "Root Touchup", "2inch": 1200, "3inch": 1400, "4inch": 1600 },
  ],
  men_treatments: [
    { service: "Hydrating Spa", short: 650, medium: 750, long: 850 },
    { service: "Anti Dandruff Spa", short: 700, medium: 800, long: 900 },
    { service: "Oil Reflection Spa", short: 1000, medium: 1200, long: 1500 },
    { service: "Head Massage", price: 250 },
    { service: "Keratin Crown", price: 1500 },
    { service: "Keratin Global", price: 3000 },
    { service: "Botox Crown", price: 2000 },
    { service: "Botox Global", price: 3500 },
    { service: "Perming Crown", price: 3500 },
    { service: "Perming Global", price: 6500 },
  ],
  women_treatments: [
    { service: "Hydrating Spa", shoulder: 800, below: 1400, waist: 1800 },
    { service: "Anti Dandruff", shoulder: 850, below: 1450, waist: 1850 },
    { service: "Oil Reflection", shoulder: 1200, below: 1900, waist: 2300 },
    { service: "Keratin", shoulder: 3000, below: 5500, waist: 7000 },
    { service: "Botox/Nanoplastia", shoulder: 4000, below: 6500, waist: 8000 },
    { service: "Smoothing", shoulder: 3000, below: 5500, waist: 7000 },
    { service: "Straightening", shoulder: 3500, below: 6000, waist: 7500 },
  ],
  skin_services: [
    { service: "Cleansing", price: 100 },
    { service: "Scrub", price: 300 },
    { service: "D-Tan", price: 500 },
    { service: "Clean Up", range: "800 - 1500" },
    { service: "Facial", range: "1200 - 2800" },
    { service: "Hydra Facial", range: "700 - 3500" },
    { service: "Body Polishing", price: 4500 },
  ],
  men_waxing: [
    { service: "Underarms", price: 200 },
    { service: "Full Hand", price: 400 },
    { service: "Full Leg", price: 500 },
    { service: "Full Body", price: 2500 },
  ],
  women_waxing: [
    { service: "Underarms", range: "150 - 350" },
    { service: "Full Hand", range: "350 - 550" },
    { service: "Full Body", range: "1200 - 2000" },
    { service: "Bikini Wax", range: "1000 - 1500" },
  ],
  threading: [
    { service: "Eyebrows", price: 60 },
    { service: "Upper Lips", price: 20 },
    { service: "Full Face", price: 150 },
  ],
  nail_services: [
    { service: "Press On Extensions", without_art: 1200, with_art: 1500 },
    { service: "Gel Extensions", without_art: 1700, with_art: 2000 },
    { service: "Acrylic Extensions", without_art: 2200, with_art: 2500 },
    { service: "Toe Extension", price: 1200 },
    { service: "Gel Polish", price: 500 },
    { service: "Chrome", price: 800 },
    { service: "Overlay (BIAB)", price: 1200 },
    { service: "Refilling", price: 1200 },
    { service: "Removal", price: 500 },
  ],
  semi_permanent: [
    { service: "Microblading & Shading", price: 1500 },
    { service: "Microblading & Pigmentation", price: 2500 },
    { service: "Lip Tinting", price: 1500 },
    { service: "Lip Liner + Tint", price: 2200 },
    { service: "BB Glow", range: "1000 - 4500" },
    { service: "Eye Lash Extension", range: "1800 - 3000" },
    { service: "Eye Liner", price: 1200 },
  ],
}

export const pricingCategories = [
  { id: 'men_haircut', label: "Men's Haircut", icon: '✂️' },
  { id: 'women_haircut', label: "Women's Haircut", icon: '✂️' },
  { id: 'hair_styling', label: 'Hair Styling', icon: '💇' },
  { id: 'men_hair_color', label: "Men's Hair Color", icon: '🎨' },
  { id: 'women_hair_color', label: "Women's Hair Color", icon: '🎨' },
  { id: 'men_treatments', label: "Men's Treatments", icon: '💆' },
  { id: 'women_treatments', label: "Women's Treatments", icon: '💆' },
  { id: 'skin_services', label: 'Skin Services', icon: '✨' },
  { id: 'men_waxing', label: "Men's Waxing", icon: '🪮' },
  { id: 'women_waxing', label: "Women's Waxing", icon: '🪮' },
  { id: 'threading', label: 'Threading', icon: '🧵' },
  { id: 'nail_services', label: 'Nail Services', icon: '💅' },
  { id: 'semi_permanent', label: 'Semi-Permanent', icon: '✨' },
]
